from __future__ import annotations

from collections.abc import Callable
from typing import Any, Protocol


class ClockPort(Protocol):
    def __call__(self) -> float: ...


class MidiInputPort(Protocol):
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def status(self) -> dict: ...


class SynthPort(Protocol):
    """Runtime-facing audio boundary; DSP and device adapters may change freely."""

    timbre: Any

    def start(self) -> None: ...
    def stop(self) -> None: ...
    def status(self) -> dict: ...
    def note_on(
        self,
        channel: int,
        midi_note: int,
        frequency_hz: float,
        velocity: int,
    ) -> int: ...
    def note_off(self, voice_id: int) -> None: ...
    def discard_voice(self, voice_id: int) -> None: ...
    def all_notes_off(self) -> None: ...
    def notes_off_for_channels(self, channels: set[int]) -> None: ...
    def set_pitch_bend(self, channel: int, value: int) -> None: ...
    def pitch_bend_factor(self, channel: int) -> float: ...
    def set_timbre(self, timbre_id: str) -> None: ...
    def set_custom_timbre(self, partials: list[tuple[float, float]]) -> None: ...
    def set_master_volume(self, value: float) -> None: ...


MidiInputFactory = Callable[
    [str, Callable[[dict], None], Callable[[dict], None]],
    MidiInputPort,
]
